#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Remove the if condition to load terminal faster

BREW_PREFIX="/opt/homebrew"

# Get the Homebrew prefix and set the completion path directly
declare BASH_COMPLETION_PATH="$BREW_PREFIX/etc/profile.d/bash_completion.sh"

# Source the bash completion file
. "$BASH_COMPLETION_PATH"

# Ensure bash completion works for `git` aliases
__git_complete g git

# Set the completion directory for compatibility with other bash-completion scripts
export BASH_COMPLETION_COMPAT_DIR="$BREW_PREFIX/etc/bash_completion.d"
