#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Ensure 
# 1. "brew" is in PATH
# 2. bash autocompletion works for "brew" itself
# different from bash_autocompletion (completions for brew-installed programs)
# has to export brew path first, otherwise autocompletion fails

# the completion file is in "$(brew --prefix 2> /dev/null)/completions/bash/brew"
# https://github.com/orgs/Homebrew/discussions/4227


# Do not condition for faster loading
eval $(/opt/homebrew/bin/brew shellenv)

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

source_bash_files() {

    declare -r CURRENT_DIRECTORY="$(pwd)"

    declare -r -a FILES_TO_SOURCE=(
        "bash_exports"
        "bash_aliases"
        "bash_autocompletion"
        "bash_colors"
        "bash_functions"
        "bash_options"
        "bash_prompt"
        "bash.local"  # For local settings that should
                      # not be under version control.
    )

    local file=""
    local i=""

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    cd "$(dirname "$(readlink "${BASH_SOURCE[0]}")")" \
        && . "../os/utils.sh"

    # shellcheck disable=SC2034
    declare -r OS="$(get_os)"

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    for i in ${!FILES_TO_SOURCE[*]}; do

        file="$HOME/.${FILES_TO_SOURCE[$i]}"

        . "$file"

    done

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    cd "$CURRENT_DIRECTORY"

}

source_bash_files
unset -f source_bash_files

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# TODO: This part will add a half second delay when launching new terminal
# https://nono.ma/anaconda-conda-slows-down-terminal-apple-silicon-m1-m2

# reset base env might help
# see https://github.com/conda-forge/miniforge/issues/296

# https://github.com/tartansandal/conda-bash-completion

# source $CONDA_ROOT/etc/profile.d/bash_completion.sh


# Directly source conda.sh for faster loading

. "/opt/homebrew/Caskroom/miniforge/base/etc/profile.d/conda.sh"


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Clear system messages (system copyright notice, the date
# and time of the last login, the message of the day, etc.).

# clear
